name: CI
on: [push, pull_request]

jobs:
  test:
  
    runs-on: ubuntu-latest
    
    strategy:
      
      fail-fast: false
      
      matrix:
        haxe:
        - latest
        - 4.3.7
        - 4.3.0
        - 4.2.5
        #- 3.4.7
        
    steps:
    
      - uses: actions/checkout@v4
      
      - name: Install haxe ${{ matrix.haxe }}
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: ${{ matrix.haxe }}
          
      - name: Print version numbers
        run: |
          haxe -version
          haxelib help

      - uses: actions/checkout@v4
        with:
          repository: HaxeFoundation/haxelib
          ref: 4.0.3
          path: haxelib
          submodules: recursive

      - name: Build haxelib
        run: |
          cd haxelib
          haxe client.hxml

      - name: Test haxelib 4.0.3
        run: |
          neko haxelib/run.n --system info dox --debug

      - name: Install dox
        run: |
          haxelib info dox --debug
          haxelib install dox --debug
          haxelib run dox --help
