name: CI
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4
      
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.2.5
          
      - name: Install dox
        run: |
          haxe --version
          haxelib help
          haxelib info dox --debug
          haxelib install dox --debug
          haxelib run dox --help
