name: CI
on: [push, pull_request]

jobs:
  test:
  
    runs-on: ubuntu-latest
    
    strategy:
      
      fail-fast: false
      
      matrix:
        haxe:
        - latest
        - 4.2.5
        - 3.4.7
        
    steps:
    
      - uses: actions/checkout@v4
      
      - name: Install haxe ${{ matrix.haxe }}
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}

      - run: |
          haxelib install haxelib --debug
          haxelib update haxelib --debug
          haxelib fixrepo --debug
      
      - name: Print version numbers
        run: |
          haxe -version
          haxelib help

      - name: Install dox
        run: |
          haxelib info dox --debug
          haxelib install dox --debug
          haxelib run dox --help
